version: "3.9"

name: lct_hr_dashboard
services:
  redis:
    image: redislabs/redismod
    ports:
      - "6744:6379"
    volumes:
      - $PWD/data:/data
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - lct_hr_dashboard_pg_data:/var/lib/postgresql/data
    ports:
      - "5667:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    # volumes:
    #   - "logs:/data"
    # ports:
    #   - "3233:3333"
    depends_on:
      - db
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.lct-hr-api.loadbalancer.server.port=3333"
      - "traefik.http.routers.lct-hr-api.tls.certresolver=le"
      - "traefik.http.routers.lct-hr-api.rule=Host(`lct-hr-api.onixx.ru`)"
      - "traefik.http.routers.lct-hr-api.entrypoints=websecure"
      - "traefik.http.routers.lct-hr-api.tls=true"
  # hr_dashboard-ui:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - api
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.beerman.loadbalancer.server.port=80"
  #     - "traefik.http.routers.beerman.tls.certresolver=le"
  #     - "traefik.http.routers.beerman.rule=Host(`lct-hr.onixx.ru`)"
  #     - "traefik.http.routers.beerman.entrypoints=websecure"
  #     - "traefik.http.routers.beerman.tls=true"

volumes:
  lct_hr_dashboard_pg_data:
