"""update_phone_variety

Revision ID: 003
Revises: 002
Create Date: 2023-12-17 08:06:29.724388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'phone',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
